// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://urkngnujfshjhrekxdhh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVya25nbnVqZnNoamhyZWt4ZGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyODYyNzMsImV4cCI6MjA0Nzg2MjI3M30.YaiNdoqkBCThRWIlBIpofo1Sm9TDiSggSQ5DziuegPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);